In [2]:
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd
#load the dataset

data=gutenberg.raw('shakespeare-hamlet.txt')



[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\tata\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [3]:
data

"[The Tragedie of Hamlet by William Shakespeare 1599]\n\n\nActus Primus. Scoena Prima.\n\nEnter Barnardo and Francisco two Centinels.\n\n  Barnardo. Who's there?\n  Fran. Nay answer me: Stand & vnfold\nyour selfe\n\n   Bar. Long liue the King\n\n   Fran. Barnardo?\n  Bar. He\n\n   Fran. You come most carefully vpon your houre\n\n   Bar. 'Tis now strook twelue, get thee to bed Francisco\n\n   Fran. For this releefe much thankes: 'Tis bitter cold,\nAnd I am sicke at heart\n\n   Barn. Haue you had quiet Guard?\n  Fran. Not a Mouse stirring\n\n   Barn. Well, goodnight. If you do meet Horatio and\nMarcellus, the Riuals of my Watch, bid them make hast.\nEnter Horatio and Marcellus.\n\n  Fran. I thinke I heare them. Stand: who's there?\n  Hor. Friends to this ground\n\n   Mar. And Leige-men to the Dane\n\n   Fran. Giue you good night\n\n   Mar. O farwel honest Soldier, who hath relieu'd you?\n  Fra. Barnardo ha's my place: giue you goodnight.\n\nExit Fran.\n\n  Mar. Holla Barnardo\n\n   Bar. 

In [8]:

#reading in a file
with open('hamlet.txt','w') as file:
    file.write(data)

In [9]:
import numpy as np
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential

In [10]:
with open('hamlet.txt','r') as file:
    text=file.read().lower()

tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])#words
total_words=len(tokenizer.word_index)+1
total_words

4818

In [11]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [12]:
#create input sequences
input_sequences=[]
for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    print(token_list)
    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1] 
        input_sequences.append(n_gram_sequence)

[1, 687, 4, 45, 41, 1886, 1887, 1888]
[]
[]
[1180, 1889, 1890, 1891]
[]
[57, 407, 2, 1181, 177, 1892]
[]
[407, 1182, 63]
[408, 162, 377, 21, 247, 882]
[18, 66]
[]
[451, 224, 248, 1, 30]
[]
[408, 407]
[451, 25]
[]
[408, 6, 43, 62, 1893, 96, 18, 566]
[]
[451, 71, 51, 1894, 567, 378, 80, 3, 273, 1181]
[]
[408, 20, 16, 1895, 114, 379, 71, 883, 491]
[2, 5, 92, 688, 58, 144]
[]
[346, 29, 6, 108, 568, 884]
[408, 14, 7, 885, 1896]
[]
[346, 64, 380, 37, 6, 47, 689, 120, 2]
[347, 1, 1897, 4, 8, 257, 492, 68, 87, 149]
[57, 120, 2, 347]
[]
[408, 5, 117, 5, 139, 68, 247, 1182, 63]
[48, 205, 3, 16, 409]
[]
[140, 2, 1898, 348, 3, 1, 493]
[]
[408, 79, 6, 46, 124]
[]
[140, 125, 1899, 322, 1183, 121, 83, 1900, 6]
[1901, 407, 258, 8, 494, 79, 6, 380]
[]
[218, 408]
[]
[140, 1902, 407]
[]
[451, 94, 24, 13, 120, 63]
[48, 7, 495, 4, 28]
[]
[451, 236, 120, 236, 46, 347]
[]
[140, 24, 258, 16, 167, 886, 131, 3, 124]
[]
[451, 5, 29, 189, 153]
[]
[140, 120, 887, 71, 19, 33, 1184]
[2, 31, 14, 50, 1903, 136, 168, 4

In [13]:
input_sequences

[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182, 63],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408, 407],
 [451, 25],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [451, 71

In [14]:
maxlen=max([len(i) for i in input_sequences])

In [15]:
#padding sequences
input_sequences=np.array(pad_sequences(input_sequences,padding='pre',maxlen=maxlen))

In [16]:
input_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]])

In [17]:
import tensorflow as tensorflow
x,y=input_sequences[:,:-1],input_sequences[:,-1]


In [18]:
y

array([ 687,    4,   45, ..., 1047,    4,  193])

In [19]:
y=tensorflow.keras.utils.to_categorical(y,num_classes=total_words)

In [20]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [22]:
##train our LSTM
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding,LSTM,GRU,Dropout
model=Sequential()
model.add(Embedding(total_words,100,input_length=maxlen-1))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation='softmax'))
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])



In [24]:
history_lstm=model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=80,verbose=1)

Epoch 1/80
644/644 [==============================] - 24s 38ms/step - loss: 6.6116 - accuracy: 0.0351 - val_loss: 6.8264 - val_accuracy: 0.0425
Epoch 2/80
644/644 [==============================] - 23s 36ms/step - loss: 6.4072 - accuracy: 0.0424 - val_loss: 6.8358 - val_accuracy: 0.0507
Epoch 3/80
644/644 [==============================] - 23s 36ms/step - loss: 6.2428 - accuracy: 0.0504 - val_loss: 6.8488 - val_accuracy: 0.0470
Epoch 4/80
644/644 [==============================] - 22s 34ms/step - loss: 6.1089 - accuracy: 0.0517 - val_loss: 6.8978 - val_accuracy: 0.0536
Epoch 5/80
644/644 [==============================] - 24s 37ms/step - loss: 5.9705 - accuracy: 0.0587 - val_loss: 6.9473 - val_accuracy: 0.0567
Epoch 6/80
644/644 [==============================] - 24s 38ms/step - loss: 5.8276 - accuracy: 0.0665 - val_loss: 6.9874 - val_accuracy: 0.0641
Epoch 7/80
644/644 [==============================] - 23s 36ms/step - loss: 5.6810 - accuracy: 0.0760 - val_loss: 7.0792 - val_accuracy:

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding,LSTM,GRU,Dropout
model_gru=Sequential()
model_gru.add(Embedding(total_words,100,input_length=maxlen-1))
model_gru.add(GRU(150,return_sequences=True))
model_gru.add(Dropout(0.2))
model_gru.add(GRU(100))
model_gru.add(Dense(total_words,activation='softmax'))
model_gru.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])






history_gru=model_gru.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=80,verbose=1)

Epoch 1/80
644/644 [==============================] - 21s 28ms/step - loss: 7.0787 - accuracy: 0.0302 - val_loss: 6.9699 - val_accuracy: 0.0208
Epoch 2/80
644/644 [==============================] - 17s 26ms/step - loss: 6.5505 - accuracy: 0.0373 - val_loss: 6.8628 - val_accuracy: 0.0509
Epoch 3/80
644/644 [==============================] - 17s 26ms/step - loss: 6.3134 - accuracy: 0.0493 - val_loss: 6.7899 - val_accuracy: 0.0563
Epoch 4/80
644/644 [==============================] - 17s 26ms/step - loss: 6.0675 - accuracy: 0.0656 - val_loss: 6.7906 - val_accuracy: 0.0647
Epoch 5/80
644/644 [==============================] - 17s 27ms/step - loss: 5.8111 - accuracy: 0.0812 - val_loss: 6.8539 - val_accuracy: 0.0703
Epoch 6/80
644/644 [==============================] - 16s 25ms/step - loss: 5.5550 - accuracy: 0.0924 - val_loss: 6.8971 - val_accuracy: 0.0742
Epoch 7/80
644/644 [==============================] - 16s 25ms/step - loss: 5.3139 - accuracy: 0.1028 - val_loss: 6.9797 - val_accuracy:

In [39]:
def predict_next_word(model,tokenizer,text,maxlen):
    token_list=tokenizer.texts_to_sequences([text])[0]
    if len(token_list)>=maxlen:
        token_list=token_list[-(maxlen-1):]
    token_list=pad_sequences([token_list],maxlen=maxlen-1,padding='pre')
    predicted=model.predict(token_list,verbose=0)
    predicted_word_index=np.argmax(predicted,axis=1)
    for word,index in tokenizer.word_index.items():
        if index==predicted_word_index:
            return word
    return None

In [40]:
input_text='to be or not to be'
max_len=model.input_shape[1]+1
next_word_lstm=predict_next_word(model,tokenizer,input_text,maxlen=max_len)
next_word_gru=predict_next_word(model,tokenizer,input_text,maxlen=max_len)
print(next_word_lstm,next_word_gru)

done done


In [ ]:
model.save('next_word_lstm.h5')
model.save('next_word_gru.h5')
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)


c:\Users\tata\Downloads\RNN model\venv_rnn\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
